// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
int32_t pA1 = A1_pos[0];
int32_t A1_end = A1_pos[1];
int32_t iz = 0;
int32_t z1_end = z1_dimension;
while (pA1 < A1_end) {
  int32_t iA = A1_coord[pA1];
  int32_t pz1 = iz;
  int32_t py1 = iz;
  if (iA == iz) {
    for (int32_t pA2 = A2_pos[pA1]; pA2 < A2_pos[(pA1 + 1)]; pA2++) {
      int32_t jA = A2_coord[pA2];
    }
  }
  else {
  }
  pA1 += (int32_t)(iA == iz);
  iz++;
}
while (iz < z1_end) {
  int32_t pz10 = iz;
  int32_t py10 = iz;
  iz++;
}

allocate y_vals[y1_dimension]
y_vals_size = y1_dimension;
