// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
for (int32_t py = 0; py < y1_dimension; py++) {
  y_vals[py] = 0;
}
int32_t pA1 = A1_pos[0];
int32_t A1_end = A1_pos[1];
int32_t iz = 0;
int32_t z1_end = z1_dimension;
while (pA1 < A1_end) {
  int32_t iA = A1_coord[pA1];
  int32_t pz1 = iz;
  int32_t py1 = iz;
  if (iA == iz) {
    double tj = 0;
    for (int32_t pA2 = A2_pos[pA1]; pA2 < A2_pos[(pA1 + 1)]; pA2++) {
      int32_t jA = A2_coord[pA2];
      tj += A_vals[pA2] * x_vals[jA];
    }
    y_vals[py1] = alpha_vals[0] * tj + z_vals[pz1];
  }
  else {
    y_vals[py1] = z_vals[pz1];
  }
  pA1 += (int32_t)(iA == iz);
  iz++;
}
while (iz < z1_end) {
  int32_t pz10 = iz;
  int32_t py10 = iz;
  y_vals[py10] = z_vals[pz10];
  iz++;
}
