// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
for (int32_t iA = 0; iA < A1_dimension; iA++) {
  for (int32_t jA = 0; jA < A2_dimension; jA++) {
    int32_t pA2 = iA * A2_dimension + jA;
  }
}

allocate y_vals[y1_dimension]
y_vals_size = y1_dimension;
