// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "y(i)=A(i,j)*x(j)" -f=y:d:0 -f=A:dd:0,1 -f=x:d:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <complex.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  int y1_dimension = (int)(y->dimensions[y->mode_ordering[0]]);
  double* restrict y_vals = (double*)(y->vals);
  int y_vals_size = y->vals_size;
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  for (int32_t iA = 0; iA < A1_dimension; iA++) {
    for (int32_t jA = 0; jA < A2_dimension; jA++) {
      int32_t pA2 = iA * A2_dimension + jA;
    }
  }

  y_vals = (double*)malloc(sizeof(double) * y1_dimension);
  y_vals_size = y1_dimension;
  y->vals = (uint8_t*)y_vals;
  y->vals_size = y_vals_size;
  return 0;
}

int compute(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  double* restrict y_vals = (double*)(y->vals);
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  double* restrict x_vals = (double*)(x->vals);
  #pragma omp parallel for
  for (int32_t iA = 0; iA < A1_dimension; iA++) {
    double tj = 0;
    for (int32_t jA = 0; jA < A2_dimension; jA++) {
      int32_t pA2 = iA * A2_dimension + jA;
      tj += A_vals[pA2] * x_vals[jA];
    }
    y_vals[iA] = tj;
  }
  return 0;
}
